### PR TITLE
Remove onLanguage:java activation event

### PR DESCRIPTION
**Pull request by xorye**
Signed-off-by: David Kwon <dakwon@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
@xorye could you explain please what you do that. If I remember I did that to manage codelens and hover in java files.

**Comment by xorye** [comment]
The main reason was that if I have a Java file from a regular Java project open (not a Quarkus project), and I try hover, an error message pops out from the 'Quarkus Tools' output:
gif showing the hover error

**Comment by angelozerr** [comment]
Have you the same error once java jdt ls is started? 

IMHO we must discover why we have this bug and try to fix it.

**Comment by angelozerr** [comment]
@xorye I cannot reproduce this issue (screenshot image is not available). Perhaps my refactor with hover as extension point fixes the problem?

**Comment by xorye** [comment]
Here's the gif of the problem I was describing before:
gif showing the hover error

However, now I can't reproduce it either

**Comment by angelozerr** [comment]
> However, now I can't reproduce it either

@xorye I close this issue since problem is gone, but if you have problem again, please reopen it.

**Pull request closed without merging**
