### PR TITLE
Add different ways to open new generated project

### LINKED ISSUE #157: Provide option to add created new project folder to multi-root VS Code workspace
Currently when the user activates the "Quarkus: Generate a Maven Project" command, the result is a whole new workbench window with the new project folder as the root. I suspect this is due to the old single folder workspace in VS Code. Now that VS Code has multi-root workspaces (https://code.visualstudio.com/docs/editor/multi-root-workspaces) it would be much less jarring to the user to have the new folder simply added to the workspace rather than opening an entirely separate window. Or at least it would be good to have the option to go either way.

### PR DESCRIPTION
**Pull request by xorye**
Fixes #157

Generating a new project with a workspace or folder open: 
image

Generating a new project with nothing open:
image

Signed-off-by: David Kwon <dakwon@redhat.com>

### CODE REVIEW

**Comment by xorye** [comment]
Tested on Windows 10 and Fedora 30

**Comment by fbricon** [comment]
Generating a new project with nothing open: should directly open in the current window, no dialog necessary

**Comment by fbricon** [comment]
I'm getting this error, when running the generate project command on a new window with no open folders: 
Screen Shot 2019-12-05 at 3 26 30 PM

**Comment by xorye** [comment]
Here is the issue I created about that^

https://github.com/microsoft/vscode/issues/86419

**Comment by fbricon** [comment]
Nice work @xorye!

**Pull request merged**
