### PR TITLE
Use `vscode.env.appName` instead of hardcoding `Visual Studio Code`

### PR DESCRIPTION
**Pull request by fbricon**
Similar to https://github.com/redhat-developer/vscode-java/issues/1066

### CODE REVIEW

**Review by xorye — CHANGES_REQUESTED** [review]
This only affects the title in the tab:
image

One moment, I will add comments on what needs to change

**Comment by xorye** [comment]
https://github.com/redhat-developer/vscode-quarkus/blob/fa4e971d70dc51f05b30f07d0407175a59cfbe61/src/webviews/WelcomeWebview.ts#L75-L80

The title can be sent to the webview's html like this:

```
    const data = {
      title: `Quarkus Tools for ${vscode.env.appName}`,
      checkboxValue: QuarkusConfig.getAlwaysShowWelcomePage(),
      cssUri: this.getCssUri(),
      cspSource: this._panel.webview.cspSource,
      jsUri: this.getJsUri(),
    };
```

**Comment by xorye** [comment]
https://github.com/redhat-developer/vscode-quarkus/blob/fa4e971d70dc51f05b30f07d0407175a59cfbe61/webviews/templates/welcome.ejs#L14

should be changed to 

```
<h2 class="title-header"><%= title %></h2>
```

**Comment by fbricon** [comment]
Nice catch! And I also missed some text within the page. Once fixed that looks like:
Screen Shot 2019-10-31 at 6 37 47 PM

**Comment by xorye** [comment]
Oops, I overlooked that.

In that case, instead of supplying the whole title,  maybe it should supply just the appName:

```
    const data = {
      appName: vscode.env.appName,
      checkboxValue: QuarkusConfig.getAlwaysShowWelcomePage(),
      cssUri: this.getCssUri(),
      cspSource: this._panel.webview.cspSource,
      jsUri: this.getJsUri(),
    };
```
and put `<%= appName %>` throughout the html.

Because in your screenshot, it saying "development in Quarkus Tools for Visual Studio Code - Insiders" when (I think) we want "development in Visual Studio Code - Insiders"

**Comment by fbricon** [comment]
Updated

**Comment by xorye** [comment]
@fbricon Thank you, looks great

**Pull request merged**
