### PR TITLE
Implement server and extension build scripts

### PR DESCRIPTION
**Pull request by xorye**
This PR replaces PR #10 .

All of the changes requested in #10 has been completed for this PR.
Also @fbricon , the wildcard `*` for the extension name doesn't seem to work in the [package.json](https://github.com/xorye/vscode-quarkus/blob/9f2409090bcf3514cf06404c4e0d4b2830ca370a/package.json#L41). Is there a workaround?

Signed-off-by: David Kwon <dakwon@redhat.com>

### CODE REVIEW

**Comment by fbricon** [comment]
the workaround is for the gulp script to rename the file to a version-less jar, that you can reference in the package.json

**Comment by fbricon** [comment]
alternatively, the maven build could generate a version-less jar

**Comment by xorye** [comment]
I went with the first option for now

**Comment by xorye** [comment]
@fbricon I changed the version to 0.15.0 and ran npm install

**Pull request merged**
