### PR TITLE
Disabled Qute language id pop-up after first appearance

### PR DESCRIPTION
**Pull request by AlexXuChen**
Disabled Qute language id pop-up after first appearance and removed `documentCache`

Fix for #451 

Signed-off-by: Alexander Chen <alchen@redhat.com>

### CODE REVIEW

**Comment by rgrunber** [comment]
LGTM. I wouldn't mind confirming but this should disable the popup after the first time.

**Comment by AlexXuChen** [comment]
> LGTM. I wouldn't mind confirming but this should disable the popup after the first time.

Yep, working as intended:
Peek 2022-01-31 11-51

Something I noticed however: I was debugging workspaceTrust, and after disabling and re-enabling to test a vscode-xml fix, the `quarkus.tools.propertiesLanguageMismatch` was set to `ignore`, even though the default is `forceQuarkus`, so the language id was never forced. I never configured the setting, and even cleared my workspace cache before testing the untrusted workspace, so it seems unusual for this to happen. Thoughts?

**Comment by rgrunber** [comment]
> > LGTM. I wouldn't mind confirming but this should disable the popup after the first time.
> 
> Something I noticed however: I was debugging workspaceTrust, and after disabling and re-enabling to test a vscode-xml fix, the `quarkus.tools.propertiesLanguageMismatch` was set to `ignore`, even though the default is `forceQuarkus`, so the language id was never forced. I never configured the setting, and even cleared my workspace cache before testing the untrusted workspace, so it seems unusual for this to happen. Thoughts?

Then let's merge this.

`Disable Language Updating` will set it to ignore https://github.com/redhat-developer/vscode-quarkus/blob/master/src/extension.ts#L128 .

**Comment by AlexXuChen** [comment]
> `Disable Language Updating` will set it to ignore https://github.com/redhat-developer/vscode-quarkus/blob/master/src/extension.ts#L128 .

Ah so I must have disabled it once.

**Pull request merged**
