### PR TITLE
Ideas for the welcome page

### PR DESCRIPTION
**Pull request by xorye**
For #53 

WELCOME.md contains my suggestions for a welcome page.

For the "View quickstart projects" link, I think it would be nice if it could link to a new VSCode webview presenting the projects, similar to how the [IBM Blockchain Platform VS Code extension](https://marketplace.visualstudio.com/items?itemName=IBMBlockchain.ibm-blockchain-platform) has their welcome page link to separate VSCode webviews. The new webview would show the list of projects and also would reference the [original quickstarts github repository](https://github.com/quarkusio/quarkus-quickstarts).

Same with the "View guides" link, I think it would be nice if it would open a new webview containing the guides, and also reference the source of all guides: https://quarkus.io/guides/.

I'm not sure if having new webviews is entirely necessary though. I think it would just look neat/organized.

Signed-off-by: David Kwon <dakwon@redhat.com>

### CODE REVIEW

**Comment by xorye** [comment]
Screenshot of WELCOME.md:

image

**Comment by fbricon** [comment]
I think that's a good start. I'm curious to see how vscode behaves when both the java extension pack and quarkus try to open their welcome page. Also, we might get this quarkus extension featured on the java extension pack welcome page (we need to decide how).I'm a bit afraid of redundancy

**Comment by xorye** [comment]
I've made the webview for the welcome page.
It now looks like this:
image

I've rebased this branch with the branch for this PR: https://github.com/redhat-developer/vscode-quarkus/pull/99

For now, the welcome page can be viewed only by calling a new VSCode command: "Quarkus: Welcome".

**Comment by maxandersen** [comment]
this looks great - whats the best way to "test" it ? any builds that have it ? 

also - what does "Open Quarkus Project" do vs "Create Quarkus Project" ?

**Comment by xorye** [comment]
"Create Quarkus Project" opens the wizard to create a new project, while "Open Quarkus Project" opens a folder chooser window.

Maybe "Open Folder" would be better?

**Comment by maxandersen** [comment]
maybe just me - but I would just leave out the "Open Quarkus Project" ... does other welcome screens do it like this too ?

**Comment by xorye** [comment]
Not that I know of. I've checked the java extension pack. I'll leave it out since opening a folder can be easily done in other ways

**Comment by xorye** [comment]
The welcome page now looks like this:
image

This PR adds a new user config setting:
image

On extension activation, the extension checks if this setting is set to true. If true, the welcome page will display. This setting is true by default.

A good enhancement would be to add a checkbox in the welcome page to control this setting, like the java extension pack does:
image

@fbricon @maxandersen do we want the checkbox in this PR?

When testing this PR within VS Code, make sure to delete vscode-quarkus/node_modules/ and run `npm install`. I can also provide a vsix.

**Comment by maxandersen** [comment]
what is the default value for that checkbox for Java welcome page ? I would say mimick that rather than another approach.

**Comment by xorye** [comment]
Here's an update for the welcome page:
image

The default value for that checkbox for Java welcome page is true. The checkbox for the welcome page in the screenshot now acts the same as the Java Extension pack's welcome page.

**Comment by angelozerr** [comment]
What is the status of this PR? @maxandersen @gorkem @fbricon do you think we can merge this PR?

**Comment by maxandersen** [comment]
looks good to me.

**Review by maxandersen — APPROVED** [review]

**Comment by angelozerr** [comment]
Thanks @maxandersen for your feedback!

**Pull request merged**
