### PR TITLE
Improve application.properties textmate grammar

### LINKED ISSUE #233: Improve application.properties TextMate grammar
There are pros and cons between the old textmate grammar and the new textmate grammar introduced in https://github.com/redhat-developer/vscode-quarkus/pull/230

Here are some cases where the two grammars act differently.
### Multiline property keys (old grammar is preferable):
Old grammar:
image

New grammar:
image

### Multiline property values (new grammar is preferable):
Old grammar:
image

New grammar:
image

### Apostrophes (old grammar is preferable):
Old grammar:
image

New grammar:
image

For the new grammar, the issue about the apostrophes is here: https://github.com/textmate/ini.tmbundle/issues/3 and the PR that fixes seems to fix that issue is here: https://github.com/textmate/ini.tmbundle/pull/1

I've thought of three approaches we can take (please, by all means, suggest more approaches if there are better ones). The approaches are in no particular order.

To satisfy the cases above, we can either :
* Go back to the old grammar and build on top of it

OR

* Create issues in VS Code's repository to fix the grammars

OR

* Build on top of the VS Code's grammar ourselves since 2. might take a long time

### PR DESCRIPTION
**Pull request by xorye**
Fixes #233 

The PR https://github.com/textmate/ini.tmbundle/pull/1 that fixes this apostrophe problem:
image

uses the `\K` regex pattern, which VS Code does not seem to support: https://github.com/microsoft/vscode/issues/93426

Therefore in VS Code, the regexes with `\K` in that PR does not match with anything, therefore does not highlight anything in orange, therefore appearing to solve the issue in VS Code.

The PR I am making right now, contains TextMate grammar from https://github.com/microsoft/vscode/blob/master/extensions/ini/syntaxes/ini.tmLanguage.json, removes source ini specific grammar (like using `;` for commenting), removes matching the single or double quotes (which removes the orange string highlighting alltogether), and adds support for multi-line property keys and number highlighting.

Examples:
```
quarkus\
.application\
.name=name

quarkus.application.version=123
```
image

```
quarkus.application.name=long\
application\
name

quarkus.http.port = 1234
```
image

```
quarkus.application.name=David's application
quarkus.http.port=8080
```
image

```
org.acme.restclient.CountriesService/mp-rest/url=https://restcountries.eu/rest
configKey/mp-rest/url = 
```
image

```
# comment
quarkus.\
http.\
port = { \
  "name": "EpochMillis" \
}

# comment
quarkus.application.name=my app name
```
image

Signed-off-by: David Kwon <dakwon@redhat.com>

### CODE REVIEW

**Review by fbricon — CHANGES_REQUESTED** [review]
It doesn't like profiles, eg. `%dev.quarkus.http.port=8080`:

Screen Shot 2020-03-26 at 5 07 36 PM

**Comment by xorye** [comment]
Fixed
image

**Comment by fbricon** [comment]
weird, it doesn't work for me

**Comment by xorye** [comment]
It should work now

**Comment by fbricon** [comment]
Nice work @xorye !

**Pull request merged**
