### PR TITLE
Provide HTML support for Qute HTML templates

### LINKED ISSUE #483: Provide HTML support for Qute HTML templates
Currently, Qute html templates only get Qute support. HTML validation and completion are missing. Would be nice if we could hook up the HTML LS to qute-html templates.

### PR DESCRIPTION
**Pull request by angelozerr**
Provide HTML support for Qute HTML templates

Fixes #483

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
To test the PR you need to instal `VSCode Insiders` which provides my contribution to vscode https://github.com/microsoft/vscode/pull/146731

Open a Qute HTML template  and you should see the HTML (completion for HTML elements, autoclose, etc) and Qute support both. Here a little demo:

QuteHTMLSupport

**Review by rgrunber — COMMENTED** [review]
Change works very well :)

So we should ideally release vscode-quarkus 1.12.0 only once VS Code 1.70.0 (currently insiders) is released ? Do we want to set the vscode/engine to 1.70.0 for this feature ?

The only downside I'm seeing is those using an older VS Code with a newer Quarkus extension will lose even `<` auto-completion (it will be gone, but the new API from html feature also won't be present pre-1.70.0).

**Comment by angelozerr** [comment]
> Change works very well :)

Great!

> So we should ideally release vscode-quarkus 1.12.0 only once VS Code 1.70.0 (currently insiders) is released ? 

I don't thing, since it is just a dclaration in package.json, it will break nothing.

> Do we want to set the vscode/engine to 1.70.0 for this feature ?

I don't know ?

>The only downside I'm seeing is those using an older VS Code with a newer Quarkus extension will lose even < auto-completion (it will be gone, but the new API from html feature also won't be present pre-1.70.0).

I think it is very annoying to have this feature because if you want to write Qute #if expression with `<`, it will generate `>` which is very annoying. I think it is better to remove that for any version.

**Review by rgrunber — APPROVED** [review]

**Comment by angelozerr** [comment]
@rgrunber do you think we can merge the PR, or do you want to wait for 1.70 release of vscode? Do you want to update the vscode engine?

**Pull request merged**
