### PR TITLE
Display errors in Qute after building Quarkus application

### LINKED ISSUE #508: Display error when Quarkus application is built for Qute
Once https://github.com/quarkusio/quarkus/pull/25810 will be merged, we could display errors in Qute template file by using `problemMatcher` from the task.

See https://github.com/quarkusio/quarkus/issues/25724 for detail of this issue.

### PR DESCRIPTION
**Pull request by JessicaJHee**
image

Fixes #508 

Signed-off-by: Jessica He <jhe@redhat.com>

### CODE REVIEW

**Comment by JessicaJHee** [comment]
To have the proper error range, I need to use `location: "(lineStart,charStart,lineEnd,charEnd)"`. If there are no other ways to find this, I will create an issue to see if it's possible to have it in the error message. 

`[1] ItemResource/items.html:13:22 - {item.pric}: Property/method [pric] not found on class [org.acme.qute.Item] nor handled by an extension method
`

Looking at this error message, I believe we should highlight the code inside '{}'?

**Comment by angelozerr** [comment]
> To have the proper error range, I need to use location: "(lineStart,charStart,lineEnd,charEnd)". If there are no other ways to find this, I will create an issue to see if it's possible to have it in the error message.

Indeed, I suggest that you create an issue to https://github.com/quarkusio/quarkus/issues but if it is not possible for doing that, they should fix the start location for: 

`[1] ItemResource/items.html:13:22 - {item.pric}: Property/method [pric] not found on class [org.acme.qute.Item] nor handled by an extension method`

The location should be  `{item.|pric}` instead of  `|{item.pric}`. I have the impression that if they fixed that, it should work better (price will be higlighted correctly).

**Comment by JessicaJHee** [comment]
Related issue in quarkus to change the error location: 
https://github.com/quarkusio/quarkus/issues/26479

**Comment by JessicaJHee** [comment]
After this change (https://github.com/quarkusio/quarkus/pull/26622), the location of the error is now consistent, but still only highlights the opening bracket. 

```
[1] ItemResource/items.html:13:13 - {item.pric}: Property/method [pric] not found on class [org.acme.qute.Item] nor handled by an extension method
[2] ItemResource/items.html:16:47 - {item.discountedPriceee}: Property/method [discountedPriceee] not found on class [org.acme.qute.Item] nor handled by an extension method
```

image

**Review by datho7561 — APPROVED** [review]
Works pretty good! I think it's worth noting somewhere that this only works for checked templates. If you do a template that isn't compiled until runtime, then the project compiles and starts even if there's errors in it. The runtime error reported by Quarkus is different, and doesn't include the offset:

```
2022-07-21 14:40:13,959 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /hello failed, error id: 5592a439-4e2b-4208-8802-34a8920e1e86-1: org.jboss.resteasy.spi.UnhandledException: io.quarkus.qute.TemplateException: Rendering error in template [hello.html] line 4: Entry "asdfasdflasiudhfiuaerb" not found in the data map in expression {asdfasdflasiudhfiuaerb}
```

**Comment by rgrunber** [comment]
@datho7561 , feel free to merge if nothing else remaining as we've confirmed this will work for compile-time. We can address the runtime issues in a future change.

**Pull request merged**
