### PR TITLE
Fix casting error when finding quarkus debug command

### LINKED ISSUE #339: Starting debugger in a Quarkus project that contains a node_modules/ fails
Make this folder structure, using the default Quarkus and Svelte example respectively:

```
 v quarkus-project
 | v src
 | | v main
 | | | v frontend
 | | | | package.json
 | | | | > node_modules
 | | | | > src
 | | | | ...
 | | | > java
 | | | ...
 | pom.xml
 | ...
```

If you try to debug the Quarkus project, it appears to do nothing.

### PR DESCRIPTION
**Pull request by datho7561**
Closes #339

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by fbricon** [comment]
fix works for me

**Comment by datho7561** [comment]
Okay, just need to test to see if the glob exclusion of `node_modules` is actually doing anything.

**Comment by datho7561** [comment]
The `node_modules` avoiding glob pattern didn't noticeably improve the performance over the other change, so I removed it.

**Review by rgrunber — APPROVED** [review]
This fixes the issue for me.

Stacktrace from before is :

```
Exception has occurred: TypeError: Cannot read property 'includes' of undefined
t isQuarkusDevTask (/home/rgrunber/git/vscode-quarkus/dist/extension.js:66268:32)
	at /home/rgrunber/git/vscode-quarkus/dist/extension.js:66228:20
	at Array.filter (<anonymous>)
	at Object.<anonymous> (/home/rgrunber/git/vscode-quarkus/dist/extension.js:66227:31)
	at Generator.next (<anonymous>)
	at fulfilled (/home/rgrunber/git/vscode-quarkus/dist/extension.js:66189:58)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Pull request merged**
