### PR TITLE
Remove vscode-extension-tester-native

### LINKED ISSUE #574: `vscode-extension-tester-native` is deprecated
See https://www.npmjs.com/package/vscode-extension-tester-native

We should assess if we need it. If we remove it, I think we can avoid the dependency on opencv for the tests.

### PR DESCRIPTION
**Pull request by datho7561**
This prevents opencv from being compiled during the UI tests.

Closes #574

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by datho7561** [comment]
@JessicaJHee if you have time, do you think you could review this PR? This one is more important than https://github.com/redhat-developer/vscode-quarkus/pull/582

**Comment by JessicaJHee** [comment]
If I understand correctly, we can remove this because we don't use native dialogs? And I'm also wondering if the test failures on this PR are relevant?

**Comment by datho7561** [comment]
Let me fix the test failures, those are my bad

**Comment by datho7561** [comment]
> we don't use native dialogs?

I think so. According to https://www.npmjs.com/package/vscode-extension-tester-native it's deprecated and there is a workaround if we need the functionality it provides.

**Comment by datho7561** [comment]
Tests should work now (except for https://github.com/redhat-developer/vscode-quarkus/pull/603)

**Comment by datho7561** [comment]
@rgrunber if you have time, could you please review this PR? If not, I understand, this PR isn't that important

**Pull request merged**
