### PR TITLE
Support for user tag

### PR DESCRIPTION
**Pull request by angelozerr**
Support for user tag

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by fbricon** [comment]
When opening templates from binaries, the file languageId is not set to qute-* (try with `#ifError` in https://github.com/FroMage/quarkus-renarde-todo/blob/main/src/main/resources/templates/tags/input.html#L5)

**Comment by angelozerr** [comment]
> When opening templates from binaries, the file languageId is not set to qute-* 

Indeed I have seen that too, but it's an issue for vscode-quarkus /cc @AlexXuChen .

**Comment by fbricon** [comment]
If you set the languageId to qute-*, the server logs an exception:
```
SEVERE: Error while matching uri 'jdt://jarentry/templates/tags/authenticityToken.html?%3Drenarde-todo%2F%5C%2FUsers%5C%2Ffbricon%5C%2F.m2%5C%2Frepository%5C%2Fio%5C%2Fquarkiverse%5C%2Frenarde%5C%2Fquarkus-renarde%5C%2F1.0.0-SNAPSHOT%5C%2Fquarkus-renarde-1.0.0-SNAPSHOT.jar%3D%2Fmaven.pomderived%3D%2Ftrue%3D%2F%3D%2Fmaven.pomderived%3D%2Ftrue%3D%2F%3D%2Fmaven.groupId%3D%2Fio.quarkiverse.renarde%3D%2F%3D%2Fmaven.artifactId%3D%2Fquarkus-renarde%3D%2F%3D%2Fmaven.version%3D%2F1.0.0-SNAPSHOT%3D%2F%3D%2Fmaven.scope%3D%2Fcompile%3D%2F' with pattern 'src/main/resources/templates/Todos/goo.html'.
java.nio.file.FileSystemNotFoundException: Provider "jdt" not installed
	at java.base/java.nio.file.Path.of(Unknown Source)
	at java.base/java.nio.file.Paths.get(Unknown Source)
	at com.redhat.qute.settings.PathPatternMatcher.matches(PathPatternMatcher.java:57)
	at com.redhat.qute.settings.QuteValidationSettings.getMatchingExcluded(QuteValidationSettings.java:150)
	at com.redhat.qute.services.commands.validation.QuteTemplateValidationStatusCommandHandler.executeCommand(QuteTemplateValidationStatusCommandHandler.java:47)

```

**Comment by fbricon** [comment]
There should be no validation for files stored in binaries

**Comment by angelozerr** [comment]
> EVERE: Error while matching uri 'jdt://jarentry/templates/tags/authenticityToken.html?%3Drenarde-todo%2F%5C%2FUsers%5C%2Ffbricon%5C%2F.m2%5C%2Frepository%5C%2Fio%5C%2Fquarkiverse%5C%2Frenarde%5C%2Fquarkus-renarde%5C%2F1.0.0-SNAPSHOT%5C%2Fquarkus-renarde-1.0.0-SNAPSHOT.jar%3D%2Fmaven.pomderived%3D%2Ftrue%3D%2F%3D%2Fmaven.pomderived%3D%2Ftrue%3D%2F%3D%2Fmaven.groupId%3D%2Fio.quarkiverse.renarde%3D%2F%3D%2Fmaven.artifactId%3D%2Fquarkus-renarde%3D%2F%3D%2Fmaven.version%3D%2F1.0.0-SNAPSHOT%3D%2F%3D%2Fmaven.scope%3D%2Fcompile%3D%2F' with pattern 'src/main/resources/templates/Todos/goo.html'.
java.nio.file.FileSystemNotFoundException: Provider "jdt" not installed

It should be fixed now, in quarkus-ls)

**Comment by fbricon** [comment]
I looked at setting the proper language id for templates embedded in jars, but there's an issue in https://github.com/redhat-developer/vscode-quarkus/blob/a033cee97aabfa67814afada9f0c8cc2ae0311dd/src/utils/languageMismatch.ts#L27

because labelsInfo is empty. I opened https://github.com/eclipse/lsp4mp/issues/220

**Comment by rgrunber** [comment]
~~Wouldn't the issue be even before `getProjecLabelInfo` ? How do we get to `tryToForceLanguageId` when the path will never match ?~~

https://github.com/redhat-developer/vscode-quarkus/blob/a033cee97aabfa67814afada9f0c8cc2ae0311dd/src/qute/commands/registerCommands.ts#L254

D'oh I'm missing your updated PR.

**Comment by rgrunber** [comment]
The change works for me now and the embedded template has its languageId updated. I think these changes are ready to merge.

**Pull request merged**
