### PR TITLE
Replace axios library with built-in fetch

### PR DESCRIPTION
**Pull request by datho7561**
Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by datho7561** [comment]
axios will still be pulled in as a transitive dependency from `@redhat-developer/vscode-redhat-telemetry`, but I've also opened a PR there to address this.

**Comment by datho7561** [comment]
@angelozerr this might fix the issue with the proxy described in https://github.com/redhat-developer/vscode-quarkus/issues/680#issuecomment-2004067318 (This is not the bug that the person filing the issue encountered, but it should be addressed).

**Comment by angelozerr** [comment]
@datho7561 I will test your PR without proxy. 

If it is working can I merge it?

**Comment by datho7561** [comment]
Okay sounds good

**Comment by angelozerr** [comment]
It works like a charm (tested without proxy), thanks @datho7561 !

**Pull request merged**
