### PR TITLE
Update vscode-redhat-telemetry to 0.6.1

### PR DESCRIPTION
**Pull request by fbricon**
Signed-off-by: Fred Bricon <fbricon@gmail.com>

### CODE REVIEW

**Comment by datho7561** [comment]
Tests are failing due to a compilation error, maybe due to the webpack change. However, the telemetry appears to be working after this change.

**Comment by rgrunber** [comment]
See https://github.com/redhat-developer/vscode-quarkus/pull/566 for explanation on the test failure.

**Review by datho7561 — APPROVED** [review]
Tests are passing locally for me now, and telemetry still works after the update.

**Comment by datho7561** [comment]
I'm trying one more thing to fix the tests (updating the testing library) and if that doesn't work, I will undo that change and merge this PR.

**Comment by datho7561** [comment]
Alright, that didn't work, so I undid it, and I'll merge this.

**Pull request merged**
